#!/bin/bash

# Default values
host=http://localhost
port=8080
user=admin

while getopts z:p:s:e:l: flag; do
  case "${flag}" in
  z) host=${OPTARG} ;;
  p) port=${OPTARG} ;;
  s) slug=${OPTARG} ;;
  e) email=${OPTARG} ;;
  l) link=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)"
  exit 1
fi

if [ -z ${slug+x} ]; then
  echo "Slug not defined (use -s)"
  exit 1
fi

if [ -z ${email+x} ]; then
  echo "Email not defined (use -e)"
  exit 1
fi

if [ -z ${link+x} ]; then
  echo "Link not defined (use -l)"
  exit 1
fi

curl --verbose \
  -X DELETE \
  -H "Connection: close" \
  "$host":"$port"/happening/"$link"/registrations/"$email"
